# Generated by Django 4.1.7 on 2023-03-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modeloVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=75, null=True, unique=True, verbose_name='modelo')),
            ],
        ),
        migrations.CreateModel(
            name='motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=75, null=True, verbose_name='Motorização')),
            ],
        ),
        migrations.CreateModel(
            name='veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niv', models.CharField(max_length=17, null=True, unique=True, verbose_name='niv')),
                ('venda', models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], default=False, null=True, verbose_name='vendido?')),
            ],
        ),
    ]
