# Generated by Django 4.1.7 on 2023-03-31 18:39

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_motor_modelo_veiculo_veiculo_modelo_veiculo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeloveiculo',
            options={'ordering': ['-nome'], 'verbose_name': ('Modelo do veículo',), 'verbose_name_plural': ('Modelos do veículo',)},
        ),
        migrations.AddField(
            model_name='veiculo',
            name='make',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Fiat'), (2, 'Chevrolet'), (3, 'Ford'), (4, 'Toyota')], null=True, verbose_name='Fabricante/Marca do veiculo'),
        ),
        migrations.AddIndex(
            model_name='modeloveiculo',
            index=models.Index(fields=['nome'], name='app_modelov_nome_f15733_idx'),
        ),
        migrations.AddIndex(
            model_name='modeloveiculo',
            index=models.Index(fields=['-nome'], name='desc_name_idx'),
        ),
        migrations.AddIndex(
            model_name='modeloveiculo',
            index=models.Index(models.OrderBy(django.db.models.functions.text.Lower('nome'), descending=True), name='lower_name_idx'),
        ),
    ]
