# Generated by Django 4.1.7 on 2023-04-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_modeloveiculo_options_veiculo_make_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=75, null=True, verbose_name='Engine')),
            ],
        ),
    ]
