# Generated by Django 4.1.7 on 2023-04-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_engine2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='engine2',
            table='app_pratica_engine',
        ),
    ]
